Feature/task 9
V31R/java_course pull request #13
Opened 2021-12-28 01:22 UTC by V31R

2021-12-28 12:11 UTC, iastafyev requested changes

2021-12-28 12:11 UTC, iastafyev commented on src/main/java/kalchenko/Main.java
> +    public DataSource dataSource() {
Spring Boot создаёт что-то аналогичное автоматически. Зачем сделано вручную?

2021-12-28 12:11 UTC, iastafyev commented on src/main/java/kalchenko/security/Users.java
> +    private Long user_id;
Неудачное именование: в java не принято разделять через '_' слова в именах полей

2021-12-28 12:11 UTC, iastafyev commented on src/main/java/kalchenko/security/UsersDetailService.java
> +        if(user == null) {
Тут `null` не может быть

2021-12-28 12:14 UTC, V31R commented on src/main/java/kalchenko/Main.java
> +    public DataSource dataSource() {
Я это делал, для того, чтобы jasypt расшифровывал пароль, который зашифрован в файле настроек.

2021-12-28 12:15 UTC, V31R commented on src/main/java/kalchenko/security/UsersDetailService.java
> +        if(user == null) {
Да, точно, выбрасываю исключение же.
Я попозже исправлю всё

2022-01-31 07:47 UTC, iastafyev approved these changes

2022-01-31 17:21 UTC, merged