Feature/task 10 2
V31R/java_course pull request #21
Opened 2022-03-10 19:01 UTC by V31R

2022-03-11 09:17 UTC, iastafyev reviewed
Не понял одного теста, а в остальном всё нормально

2022-03-11 09:17 UTC, iastafyev commented on src/test/java/kalchenko/task/TaskCRUDTest.java
> +    public void testFindByUserId(){
Не понял, что этот тест проверяет

2022-03-11 10:59 UTC, V31R commented on src/test/java/kalchenko/task/TaskCRUDTest.java
> +    public void testFindByUserId(){
Этот тест проверяет, что метод `findByUserId` находит все задачи конкретного пользователя, в данном случае 1 задачу для администратора и 1 одну задачу для простого пользователя. Будет лучше если вместо проверки размера списка сделать проверку всех задач по на пользователя, которому эти задачи должны принадлежать?

2022-03-17 13:26 UTC, iastafyev requested changes

2022-03-17 13:26 UTC, iastafyev commented on src/test/java/kalchenko/task/TaskCRUDTest.java
> +    public void testFindByUserId(){
Да вообще код очень странный. Ниже напишу комментариев по конкретным строчкам тогда, которые у меня вопросы вызвали

2022-03-17 13:26 UTC, iastafyev commented on src/test/java/kalchenko/task/TaskCRUDTest.java
> +        taskCRUD.save(task);
Зачем 2 раза сохранять?

2022-03-17 13:26 UTC, iastafyev commented on src/test/java/kalchenko/task/TaskCRUDTest.java
> +        var usersTask = taskCRUD.findAllByUserId(user.getUserID()).stream().toList();
Зачем здесь конструкция `stream().toList()`

2022-03-17 13:26 UTC, iastafyev commented on src/test/java/kalchenko/task/TaskCRUDTest.java
> +            tasks.add(taskCRUD.findByUserId(taskTemp.getId(), user.getUserID()).get());
Вот этого кода вообще не понял. В чём смысл повторно из списка грузить по `id` отдельные записи и добавлять их ещё раз в список

2022-03-17 13:26 UTC, iastafyev commented on src/test/java/kalchenko/task/TaskCRUDTest.java
> +        assertEquals(usersTask.size(), tasks.size());
Этот код не проверяет то, что задано. Для того, чтобы он его проверял, надо было, например, создать прямо в тесте несколько задач, и потом пробежать по их заранее известным идентификаторам и убедиться, что все они возвращаются. В данном случае мы полагаемся на корректность работы метода `findAllByUserId`, а это метод тестируемого объекта, которому мы не должны доверять

2022-04-01 08:10 UTC, iastafyev approved these changes

2022-04-01 08:11 UTC, merged